/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2022-07-29 03:29:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.page.feature;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/page/inc_header.jsp", Long.valueOf(1659064780855L));
    _jspx_dependants.put("/WEB-INF/tld/fn.tld", Long.valueOf(1655970478923L));
    _jspx_dependants.put("/WEB-INF/tld/struts-bean.tld", Long.valueOf(1655970478932L));
    _jspx_dependants.put("/page/inc_header_script.jsp", Long.valueOf(1658916714457L));
    _jspx_dependants.put("/WEB-INF/tld/struts-html.tld", Long.valueOf(1655970478935L));
    _jspx_dependants.put("/WEB-INF/tld/c.tld", Long.valueOf(1655970478910L));
    _jspx_dependants.put("/WEB-INF/tld/struts-logic.tld", Long.valueOf(1655970478938L));
    _jspx_dependants.put("/page/inc_menu.jsp", Long.valueOf(1658977232380L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta charset=\"utf-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("	<meta name=\"description\" content=\"\">\n");
      out.write("	<meta name=\"author\" content=\"\">\n");
      out.write("	<meta name=\"keyword\" content=\"\">\n");
      out.write("	\n");
      out.write("	<title>Service Tracking</title>\n");
      out.write("\n");
      out.write("	<!-- Bootstrap CSS -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap.min.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-theme.css\" rel=\"stylesheet\"/>\n");
      out.write("	<!-- font -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/fonts/webfont.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- font icon -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/elegant-icons-style.css\" rel=\"stylesheet\" />\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/font-awesome.min.css\" rel=\"stylesheet\" />\n");
      out.write("	<!-- datatable -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/dataTables.bootstrap.css\" rel=\"stylesheet\"/>\n");
      out.write("	<!-- Custom styles -->\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-responsive.css\" rel=\"stylesheet\" />\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/jquery-ui-10.12.1.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/style-button.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/bootstrap-select.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/css/materialize-color.css\" rel=\"stylesheet\"/>\n");
      out.write("	<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/css/sweetalert.css\" rel=\"stylesheet\"/>\n");
      out.write("\n");
      out.write("	<!-- javascripts -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.12.4.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.10.4.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-1.8.3.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery-ui-1.9.2.custom.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	<!-- for set format thai -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.ui.1.8.10.offset.datepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<!-- bootstrap -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap.min.js\"></script>\n");
      out.write("	<!-- nice scroll -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.scrollTo.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.nicescroll.js\" type=\"text/javascript\"></script>\n");
      out.write("	<!-- custom select -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.customSelect.min.js\"></script>\n");
      out.write("	\n");
      out.write("	<!--custome script for all page-->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/scripts.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- custom script for this page-->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.autosize.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.placeholder.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.slimscroll.min.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootbox.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-select.js\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/bootstrap-typeahead.js\"></script>\n");
      out.write("	\n");
      out.write("	<!-- datatable -->\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.dataTables.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/jquery.validate.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/js/quotwaiting-forquot-modal-dialog.js\" type=\"text/javascript\"></script>\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/js/sweetalert.min.js\" type=\"text/javascript\"></script>\n");
      out.write("	\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write(" 		$(document).ready(function () {\n");
      out.write(" 			\n");
      out.write(" 			$(\"#msgSuccess\").delay(800).fadeOut(1000);\n");
      out.write(" 			$(\"#msgWarning\").delay(800).fadeOut(1000);\n");
      out.write(" 			\n");
      out.write("			try {\n");
      out.write("				var variables = {};\n");
      out.write("		      	variables = {\n");
      out.write("						\"sProcessing\": \"กำลังดำเนินการ...\",\n");
      out.write("						\"sLengthMenu\": \"แสดง _MENU_  แถว\",\n");
      out.write("						\"sZeroRecords\": \"ไม่พบข้อมูล\",\n");
      out.write("						\"sInfo\": \"แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว\",\n");
      out.write("						\"sInfoEmpty\": \"แสดง 0 ถึง 0 จาก 0 แถว\",\n");
      out.write("						\"sInfoFiltered\": \"(กรองข้อมูล _MAX_ ทุกแถว)\",\n");
      out.write("						\"sInfoPostFix\": \"\",\n");
      out.write("						\"sSearch\": \"ค้นหา: \",\n");
      out.write("						\"sUrl\": \"\",\n");
      out.write("						\"oPaginate\": {\n");
      out.write("						    \"sFirst\": \"เริ่มต้น\",\n");
      out.write("						    \"sPrevious\": \"ก่อนหน้า\",\n");
      out.write("						    \"sNext\": \"ถัดไป\",\n");
      out.write("						    \"sLast\": \"สุดท้าย\"\n");
      out.write("						}\n");
      out.write("				};\n");
      out.write("			\n");
      out.write("				var options = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"oLanguage\": variables};\n");
      out.write("				var optionsHundred = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 100,\"oLanguage\": variables};\n");
      out.write("				var optionsFive = { \"aoColumnDefs\": [{ bSortable: false, aTargets: ['no-sort'] }],\"iDisplayLength\": 5,\"oLanguage\": variables};\n");
      out.write("			\n");
      out.write("				$(\".grid-default\").dataTable(options);\n");
      out.write("				$(\".grid-hundred\").dataTable(optionsHundred);\n");
      out.write("				$(\".grid-five\").dataTable(optionsFive);\n");
      out.write("			} catch (e) {\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			$.datepicker.isBuddhist ={\n");
      out.write("				isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+10',\n");
      out.write("		        buttonText: 'เลือก'\n");
      out.write("		    };\n");
      out.write("			\n");
      out.write("			$.datepicker.twomonth ={\n");
      out.write("				isBuddhist: true,\n");
      out.write("				changeMonth: false,\n");
      out.write("		        changeYear: false,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        //monthNamesShort: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+10',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2\n");
      out.write("		    };\n");
      out.write(" 			$('.i-calendar').datepicker($.datepicker.isBuddhist);\n");
      out.write("			$('.t-calendar').datepicker($.datepicker.twomonth);\n");
      out.write("			\n");
      out.write("			$( \"#dateStart\" ).datepicker({\n");
      out.write("		    	isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+5',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2,\n");
      out.write("		      	onClose: function( selectedDate ) {\n");
      out.write("		        	$( \"#dateStop\" ).datepicker( \"option\", \"minDate\", selectedDate );\n");
      out.write("		      	}\n");
      out.write("		    });\n");
      out.write("			\n");
      out.write("		    $( \"#dateStop\" ).datepicker({\n");
      out.write("		    	isBuddhist: true,\n");
      out.write("				changeMonth: true,\n");
      out.write("		        changeYear: true,\n");
      out.write("		        buttonImageOnly: false,\n");
      out.write("		        dateFormat: 'dd/mm/yy',\n");
      out.write("		        dayNames: ['อาทิตย์', 'จันทร์', 'อังคาร', 'พุธ', 'พฤหัสบดี', 'ศุกร์', 'เสาร์'],\n");
      out.write("		        dayNamesMin: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],\n");
      out.write("		        monthNames: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'],\n");
      out.write("		        monthNamesShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],\n");
      out.write("		        constrainInput: true,	\n");
      out.write("		        prevText: 'ก่อนหน้า',\n");
      out.write("		        nextText: 'ถัดไป',\n");
      out.write("		        yearRange: '-200:+5',\n");
      out.write("		        buttonText: 'เลือก',\n");
      out.write("		        numberOfMonths: 2,\n");
      out.write("		      onClose: function( selectedDate ) {\n");
      out.write("		        $( \"#dateStart\" ).datepicker( \"option\", \"maxDate\", selectedDate );\n");
      out.write("		      }\n");
      out.write("		    });\n");
      out.write("        });\n");
      out.write(" 		\n");
      out.write(" 		function showDialogContent(url,title,size){\n");
      out.write(" 			\n");
      out.write(" 			$.post(url,{}, \n");
      out.write(" 				function(results) {	 \n");
      out.write(" 				var textAndPic = $('<div id=\"dialogs\">'+results+'</div>');	\n");
      out.write(" 				var bootdialog = bootbox.dialog({\n");
      out.write(" 				    title: title,\n");
      out.write(" 				    message: textAndPic,\n");
      out.write(" 				    className: size\n");
      out.write(" 				});\n");
      out.write(" 				\n");
      out.write(" 				$('.selectpicker').selectpicker('refresh');\n");
      out.write(" 				\n");
      out.write(" 				/* dialog.init(function(){\n");
      out.write(" 				    setTimeout(function(){\n");
      out.write(" 				        dialog.find('.bootbox-body').html(textAndPic);\n");
      out.write(" 				    }, 3000);\n");
      out.write(" 				}); */	\n");
      out.write(" 				\n");
      out.write(" 			});	\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		function showDialog(url,t,w,h){    		\n");
      out.write(" 	        $('#dialogs').dialog({\n");
      out.write(" 	        	modal: true,\n");
      out.write(" 	        	show: {\n");
      out.write(" 					effect: \"fade\",\n");
      out.write(" 					duration: 200\n");
      out.write(" 				},\n");
      out.write(" 	        	title: t,\n");
      out.write(" 	            width: w,\n");
      out.write(" 	            height: h,\n");
      out.write(" 	            closeOnEscape: true,\n");
      out.write(" 	            open: function () {\n");
      out.write(" 	                $.post(url,{}, \n");
      out.write(" 	              	function(results) {	 \n");
      out.write(" 	              		$('#dialogs').html(results);	\n");
      out.write(" 	              		$('#dialogs').siblings('.ui-dialog-titlebar').find('button').blur(); \n");
      out.write(" 	              		\n");
      out.write("\n");
      out.write(" 	             	});\n");
      out.write(" 	            }\n");
      out.write(" 	        });\n");
      out.write(" 		}\n");
      out.write(" 		\n");
      out.write(" 		function showLoadingSwal() {\n");
      out.write(" 			swal({\n");
      out.write("      		  	title: \"กำลังโหลดข้อมูล...\",\n");
      out.write("      		  	imageUrl: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ui/sweetalert/image/entering-comment-loader.gif',\n");
      out.write("      			closeOnConfirm: false,\n");
      out.write("      			showCancelButton: false,\n");
      out.write("      			showConfirmButton: false,\n");
      out.write("      		});\n");
      out.write(" 		}\n");
      out.write(" 		function success() {\n");
      out.write(" 	        swal.close()\n");
      out.write(" 	    }\n");
      out.write("	</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.popup-dialog .modal-dialog { width: 700px; }\n");
      out.write("	.popuplg-dialog .modal-dialog { width: 1000px; }\n");
      out.write("</style>\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">\n");
      out.write("\n");
      out.write("	function logout() {\n");
      out.write("		Swal.fire({\n");
      out.write("			  title: 'Are you sure?',\n");
      out.write("			  text: \"You want to logout!\",\n");
      out.write("			  icon: 'warning',\n");
      out.write("			  showCancelButton: true,\n");
      out.write("			  confirmButtonColor: '#3085d6',\n");
      out.write("			  cancelButtonColor: '#d33',\n");
      out.write("			  confirmButtonText: 'Yes'\n");
      out.write("			}).then((result) => {\n");
      out.write("				if(result.isConfirmed){\n");
      out.write("					document.forms[0].mode.value = 'index';\n");
      out.write("					document.forms[0].submit();	\n");
      out.write("				}\n");
      out.write("			    \n");
      out.write("			  })\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function detail(){\n");
      out.write("		document.forms[0].mode.value = \"user\";\n");
      out.write("		document.forms[0].submit();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write(".header {\n");
      out.write("	position: fixed;\n");
      out.write("	left: 0;\n");
      out.write("	right: 0;\n");
      out.write("	z-index: 1002;\n");
      out.write("	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.176) !important;\n");
      out.write("	background-color: #00afda;\n");
      out.write("	background: -webkit-linear-gradient(left, #00afda, #1b5dab);\n");
      out.write("	background: -o-linear-gradient(right, #00afda, #1b5dab);\n");
      out.write("	background: -moz-linear-gradient(right, #00afda, #1b5dab);\n");
      out.write("	background: linear-gradient(to right, #00afda, #1b5dab);\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<header class=\"header\">\n");
      out.write("	<div class=\"top-nav notification-row\">\n");
      out.write("        <ul class=\"nav pull-right top-menu\">\n");
      out.write("	      	<div class=\"top-nav notification-row\">\n");
      out.write("				<!-- notificatoin dropdown start-->\n");
      out.write("		        <ul class=\"nav pull-right top-menu\">\n");
      out.write("					<!-- user login dropdown start-->\n");
      out.write("					<li class=\"dropdown\">\n");
      out.write("						<a href=\"#\" onclick=\"detail()\" style=\"z-index: 900;text-align: right;\">\n");
      out.write("							<span class=\"username\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.firstname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("						</a>\n");
      out.write("						<a href=\"#\" onclick=\"detail()\" style=\"font-size:15px;font-family: pridi;top: -16px;margin-bottom: -19px;z-index: 100;\">\n");
      out.write("							");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.userPosition.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("					<!-- logout-->\n");
      out.write("			      	<li class=\"dropdown topbar-user pull-right\">\n");
      out.write("						<a href=\"#\" onclick=\"logout()\" style=\"color: #fff;margin-top: 10px;\" title=\"ออกจากระบบ\">\n");
      out.write("<!-- 							<i class=\"fa fa-sign-out\" style=\"font-size: 20px;\"></i> -->\n");
      out.write("							<span style=\"font-size:16px;font-family: pridi;\">ออกจากระบบ</span>\n");
      out.write("						</a>\n");
      out.write("					</li>\n");
      out.write("		          	<!-- logout-->\n");
      out.write("		          	\n");
      out.write("				</ul>\n");
      out.write("			<!-- notificatoin dropdown end-->\n");
      out.write("			</div>\n");
      out.write("          	\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--sidebar start-->\n");
      out.write("<aside>\n");
      out.write("	<div id=\"sidebar\" class=\"nav-collapse\">\n");
      out.write("		<!-- sidebar menu start-->\n");
      out.write("		<ul class=\"sidebar-menu\">\n");
      out.write("			<li>\n");
      out.write("				<a href=\"index.htm?mode=getRequest\">\n");
      out.write("					<span>request table</span>\n");
      out.write("				</a>\n");
      out.write("			</li>\n");
      out.write("			<li>\n");
      out.write("				<a href=\"index.htm?mode=getProject\">\n");
      out.write("					<span>add request</span>\n");
      out.write("				</a>\n");
      out.write("			</li>\n");
      out.write("		</ul>\n");
      out.write("   		<!-- sidebar menu end -->\n");
      out.write("		\n");
      out.write("	</div>\n");
      out.write("</aside>\n");
      out.write('\n');
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<div class=\"wrapper\">\r\n");
      out.write("			<h2>ข้อมูลบัญชี</h2>\r\n");
      out.write("			<p>ชื่อบัญชี : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			<p>ตำแหน่ง : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.userPosition.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			<p>ชื่อ : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.firstname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			<p>นามสกุล : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.lastname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			<p>ชื่อเล่น : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.nickname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			<p>โทรศัพท์ : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("			<p>อีเมลล์ : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SSUser.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
